server:
  port: ${PORT:8080}  # Railway에서 포트는 자동 할당됨

spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://yamabiko.proxy.rlwy.net:10690/railway
    username: postgres
    password: fLGVUKxVANLevbLwWRWiNLVokudHyhVc
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: false
    open-in-view: false

  devtools:
    restart:
      enabled: false

logging:
  level:
    root: INFO
    org.hibernate.sql: debug
    org.hibernate.jdbc.bind: trace

hrbank:
  storage:
    type: local
    local:
      root-path: .hrbank/storage
  repository:
    file-directory: .hrbank
  batch:
    enabled: true
    time: "3600000"
